name: student_project

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- linearmodels
- GDAL
- pyproj
- fiona
- Shapely
- geopandas
- descartes
- pip
- pip:


